plugins:
  cdn_signed_urls_enabled:
    default: false
    client: false
    validator: EnableCDNURLSigningValidator

  cdn_signed_urls_key:
    client: false
    secret: true
    default: ''
    validator: ResetSignedCDNURLsCreds

  cdn_signed_urls_key_name:
    client: false
    default: ''
    validator: ResetSignedCDNURLsCreds

  cdn_signature_expiration_time:
    client: false
    default: 300
    min: 15
    max: 86400
